'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const os=require('os'),fs=require('fs'),path=require('path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'queue-terminal-'));process.env.FARM_DATA_DIR=dir;process.env.FARM_QUEUE_FILE=path.join(dir,'queue.json');process.env.FARM_LIFECYCLE_FILE=path.join(dir,'lifecycle.json');process.env.FARM_PRODUCTION_FILE=path.join(dir,'production.json');process.env.FARM_QUEUE_TERMINAL_RETENTION_MS=String(7*86400000);
const mod=require('../printer-bridge/farm-queue-terminal-preload.js');

test('mapea resultados lifecycle a estados terminales',()=>{assert.equal(mod.terminalState('Completado'),'completed');assert.equal(mod.terminalState('Cancelado'),'cancelled');assert.equal(mod.terminalState('Fallido'),'failed');});
test('aplica terminales, elimina payload y conserva trabajos recientes',()=>{const now=Date.now(),q={version:1,jobs:[{id:'a',state:'started',gcodeBase64:'AAAA'},{id:'b',state:'queued'}]},life={jobs:{a:{recordedAt:now-1000,result:'Completado'}}},out=mod.applyMarkers(q,life,now);const a=out.jobs.find(j=>j.id==='a');assert.equal(a.state,'completed');assert.equal(a.gcodeBase64,'');assert.ok(a.endedAt);assert.equal(out.jobs.find(j=>j.id==='b').state,'queued');});
test('terminales antiguos salen de queue pero quedan en production/lifecycle',()=>{const now=Date.now(),old=now-mod.RETENTION_MS-1,out=mod.applyMarkers({jobs:[{id:'old',state:'started'},{id:'new',state:'queued'}]},{jobs:{old:{recordedAt:old,result:'Fallido'}}},now);assert.equal(out.jobs.some(j=>j.id==='old'),false);assert.equal(out.jobs.some(j=>j.id==='new'),true);});
test('reparación de disco corrige started antes de que controller lo cargue',()=>{const now=Date.now();fs.writeFileSync(process.env.FARM_LIFECYCLE_FILE,JSON.stringify({jobs:{x:{recordedAt:now,result:'Cancelado'}}}));fs.writeFileSync(process.env.FARM_QUEUE_FILE,JSON.stringify({version:1,jobs:[{id:'x',state:'started'}]}));const r=mod.repairQueueDisk();assert.equal(r.ok,true);const q=JSON.parse(fs.readFileSync(process.env.FARM_QUEUE_FILE,'utf8'));assert.equal(q.jobs[0].state,'cancelled');});
test('production.json reconstruye un terminal aunque lifecycle.json falte',()=>{const now=Date.now();try{fs.unlinkSync(process.env.FARM_LIFECYCLE_FILE);}catch(_){}fs.writeFileSync(process.env.FARM_PRODUCTION_FILE,JSON.stringify({history:[{queueJobId:'prod-only',result:'Completado',end:now,eventId:'e1'}]}));const map=mod.markerMap();assert.equal(map['prod-only'].result,'Completado');const out=mod.applyMarkers({jobs:[{id:'prod-only',state:'started'}]},null,now);assert.equal(out.jobs[0].state,'completed');});
test('cada persist atómico futuro recibe marcadores terminales',()=>{const now=Date.now();fs.writeFileSync(process.env.FARM_LIFECYCLE_FILE,JSON.stringify({jobs:{z:{recordedAt:now,result:'Completado'}}}));const raw=JSON.stringify({version:1,jobs:[{id:'z',state:'started'}]});const rewritten=mod.rewriteQueuePayload(process.env.FARM_QUEUE_FILE+'.tmp-1',raw);assert.equal(JSON.parse(rewritten).jobs[0].state,'completed');assert.equal(mod.rewriteQueuePayload('/tmp/otra.json',raw),raw);});
